# Travis configuration
language: node_js
node_js:
    - "4"

before_script:
    - npm install
    - bower install
    
script: grunt

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
